---
engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
    exclude_fingerprints:
    - c42b72af850c2590419dfa0bb4d15004
ratings:
  paths:
  - "src/**.js"
exclude_paths:
- node_modules/**/*
- test/**/*
- lib/**/*
- dist/**/*
