---
engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - src/*.js
exclude_paths:
- "node_modules/**/*"
- "lib/**/*"
- "dist/**/*"
- "webpack.*"
- "test-scripts/**/*"
- ".codeclimate.yml"
