---
engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - src/*.js
  - test/*.js
exclude_paths:
- "node_modules/**/*"
- "lib/**/*"
- "dist/**/*"
- "webpack.*"
- "test-scripts/**/*"
- ".codeclimate.yml"
