language: node_js
cache:
  directories:
    - node_modules
    - $HOME/.yarn-cache
notifications:
  email: false
node_js:
  - '6'
before_install:
  # Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
install:
  - yarn
before_script:
  - yarn global add codecov
script:
  - yarn run test
  - yarn run build
after_success:
  - codecov
  - yarn run semantic-release
