sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
  - npm i -g codecov
script:
  - npm test
  - npm run build
after_success:
  - codecov
  - python node_modules/travis-weigh-in/weigh_in.py dist/animar.min.js
  - npm run semantic-release
after_script:
  - npm run test:browser:ci
