// flow-typed signature: e1e6d75f342d641eab4bbd03ee7d8d2b
// flow-typed version: <<STUB>>/codeweight_v^3.0.2/flow_v0.30.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'codeweight'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'codeweight' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'codeweight/dist/cli' {
  declare module.exports: any;
}

declare module 'codeweight/dist/codeweight' {
  declare module.exports: any;
}

declare module 'codeweight/dist/config-loader' {
  declare module.exports: any;
}

declare module 'codeweight/dist/index' {
  declare module.exports: any;
}

declare module 'codeweight/dist/serialize' {
  declare module.exports: any;
}

declare module 'codeweight/scripts/cli-permissions' {
  declare module.exports: any;
}

declare module 'codeweight/src/cli' {
  declare module.exports: any;
}

declare module 'codeweight/src/codeweight' {
  declare module.exports: any;
}

declare module 'codeweight/src/config-loader' {
  declare module.exports: any;
}

declare module 'codeweight/src/index' {
  declare module.exports: any;
}

declare module 'codeweight/src/serialize' {
  declare module.exports: any;
}

declare module 'codeweight/test/codeweight.spec' {
  declare module.exports: any;
}

declare module 'codeweight/test/serialize.spec' {
  declare module.exports: any;
}

declare module 'codeweight/test/testutils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'codeweight/dist/cli.js' {
  declare module.exports: $Exports<'codeweight/dist/cli'>;
}
declare module 'codeweight/dist/codeweight.js' {
  declare module.exports: $Exports<'codeweight/dist/codeweight'>;
}
declare module 'codeweight/dist/config-loader.js' {
  declare module.exports: $Exports<'codeweight/dist/config-loader'>;
}
declare module 'codeweight/dist/index.js' {
  declare module.exports: $Exports<'codeweight/dist/index'>;
}
declare module 'codeweight/dist/serialize.js' {
  declare module.exports: $Exports<'codeweight/dist/serialize'>;
}
declare module 'codeweight/scripts/cli-permissions.js' {
  declare module.exports: $Exports<'codeweight/scripts/cli-permissions'>;
}
declare module 'codeweight/src/cli.js' {
  declare module.exports: $Exports<'codeweight/src/cli'>;
}
declare module 'codeweight/src/codeweight.js' {
  declare module.exports: $Exports<'codeweight/src/codeweight'>;
}
declare module 'codeweight/src/config-loader.js' {
  declare module.exports: $Exports<'codeweight/src/config-loader'>;
}
declare module 'codeweight/src/index.js' {
  declare module.exports: $Exports<'codeweight/src/index'>;
}
declare module 'codeweight/src/serialize.js' {
  declare module.exports: $Exports<'codeweight/src/serialize'>;
}
declare module 'codeweight/test/codeweight.spec.js' {
  declare module.exports: $Exports<'codeweight/test/codeweight.spec'>;
}
declare module 'codeweight/test/serialize.spec.js' {
  declare module.exports: $Exports<'codeweight/test/serialize.spec'>;
}
declare module 'codeweight/test/testutils.js' {
  declare module.exports: $Exports<'codeweight/test/testutils'>;
}
