// flow-typed signature: fa7b04b64be1414086407012920a4e46
// flow-typed version: <<STUB>>/saucie_v^1.4.0/flow_v0.30.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'saucie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'saucie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'saucie/examples/specs/jasmine/hello_spec' {
  declare module.exports: any;
}

declare module 'saucie/examples/specs/qunit/hello_spec' {
  declare module.exports: any;
}

declare module 'saucie/examples/src/hello' {
  declare module.exports: any;
}

declare module 'saucie/lib/argv' {
  declare module.exports: any;
}

declare module 'saucie/lib/bin' {
  declare module.exports: any;
}

declare module 'saucie/lib/config' {
  declare module.exports: any;
}

declare module 'saucie/lib/connect' {
  declare module.exports: any;
}

declare module 'saucie/lib/disconnect' {
  declare module.exports: any;
}

declare module 'saucie/lib/get-test-results' {
  declare module.exports: any;
}

declare module 'saucie/lib/index' {
  declare module.exports: any;
}

declare module 'saucie/lib/js-testing-reporter-adapter/jasmine-reporter' {
  declare module.exports: any;
}

declare module 'saucie/lib/js-testing-reporter-adapter/mocha-reporter' {
  declare module.exports: any;
}

declare module 'saucie/lib/js-testing-reporter-adapter/qunit-reporter' {
  declare module.exports: any;
}

declare module 'saucie/lib/js-testing-reporter' {
  declare module.exports: any;
}

declare module 'saucie/lib/launch' {
  declare module.exports: any;
}

declare module 'saucie/lib/remote-browser' {
  declare module.exports: any;
}

declare module 'saucie/lib/tunnel' {
  declare module.exports: any;
}

declare module 'saucie/lib/update-job-status' {
  declare module.exports: any;
}

// Filename aliases
declare module 'saucie/examples/specs/jasmine/hello_spec.js' {
  declare module.exports: $Exports<'saucie/examples/specs/jasmine/hello_spec'>;
}
declare module 'saucie/examples/specs/qunit/hello_spec.js' {
  declare module.exports: $Exports<'saucie/examples/specs/qunit/hello_spec'>;
}
declare module 'saucie/examples/src/hello.js' {
  declare module.exports: $Exports<'saucie/examples/src/hello'>;
}
declare module 'saucie/lib/argv.js' {
  declare module.exports: $Exports<'saucie/lib/argv'>;
}
declare module 'saucie/lib/bin.js' {
  declare module.exports: $Exports<'saucie/lib/bin'>;
}
declare module 'saucie/lib/config.js' {
  declare module.exports: $Exports<'saucie/lib/config'>;
}
declare module 'saucie/lib/connect.js' {
  declare module.exports: $Exports<'saucie/lib/connect'>;
}
declare module 'saucie/lib/disconnect.js' {
  declare module.exports: $Exports<'saucie/lib/disconnect'>;
}
declare module 'saucie/lib/get-test-results.js' {
  declare module.exports: $Exports<'saucie/lib/get-test-results'>;
}
declare module 'saucie/lib/index.js' {
  declare module.exports: $Exports<'saucie/lib/index'>;
}
declare module 'saucie/lib/js-testing-reporter-adapter/jasmine-reporter.js' {
  declare module.exports: $Exports<'saucie/lib/js-testing-reporter-adapter/jasmine-reporter'>;
}
declare module 'saucie/lib/js-testing-reporter-adapter/mocha-reporter.js' {
  declare module.exports: $Exports<'saucie/lib/js-testing-reporter-adapter/mocha-reporter'>;
}
declare module 'saucie/lib/js-testing-reporter-adapter/qunit-reporter.js' {
  declare module.exports: $Exports<'saucie/lib/js-testing-reporter-adapter/qunit-reporter'>;
}
declare module 'saucie/lib/js-testing-reporter.js' {
  declare module.exports: $Exports<'saucie/lib/js-testing-reporter'>;
}
declare module 'saucie/lib/launch.js' {
  declare module.exports: $Exports<'saucie/lib/launch'>;
}
declare module 'saucie/lib/remote-browser.js' {
  declare module.exports: $Exports<'saucie/lib/remote-browser'>;
}
declare module 'saucie/lib/tunnel.js' {
  declare module.exports: $Exports<'saucie/lib/tunnel'>;
}
declare module 'saucie/lib/update-job-status.js' {
  declare module.exports: $Exports<'saucie/lib/update-job-status'>;
}
