// flow-typed signature: 9941c293a9cde3ecfed3bf9a649c29e1
// flow-typed version: <<STUB>>/seamless-immutable_v^6.3.0/flow_v0.30.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'seamless-immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'seamless-immutable' {
  declare type Immutable<T: Object | Array<*>> = T & {
    // Array methods
    flatMap(fn: Function): Array<any>;
    asObject(fn: Function): Object;
    asMutable(): Array<any>;
    // Object methods
    merge(collection: Array<any> | Object, deep?: Object): Object;
    set(key: string, value: any): Object;
    setIn(keyPath: Array<string>, value: any): Object;
    update(key: string, fn: Function): Object;
    updateIn(keyPath: Array<string>, fn: Function): Object;
    without(fn: Function): Object;
    without(keys: Array<string>): Object;
    without(...keys: Array<string>): Object;
    asMutable(): Array<any> | Object;
  };

  declare function from<T: Object | Array<*>> (spec: T): Immutable<T>;

  declare type Default = {
    from: typeof from;
    isImmutable: (x: *) => boolean
  };

  declare module.exports: Default;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'seamless-immutable/benchmark' {
  declare module.exports: any;
}

declare module 'seamless-immutable/Gruntfile' {
  declare module.exports: any;
}

declare module 'seamless-immutable/seamless-immutable.development' {
  declare module.exports: any;
}

declare module 'seamless-immutable/seamless-immutable.development.min' {
  declare module.exports: any;
}

declare module 'seamless-immutable/seamless-immutable.production.min' {
  declare module.exports: any;
}

declare module 'seamless-immutable/src/seamless-immutable' {
  declare module.exports: any;
}

declare module 'seamless-immutable/test/Immutable.isImmutable.spec' {
  declare module.exports: any;
}

declare module 'seamless-immutable/test/Immutable.spec' {
  declare module.exports: any;
}

declare module 'seamless-immutable/test/ImmutableArray.spec' {
  declare module.exports: any;
}

declare module 'seamless-immutable/test/ImmutableArray/test-asMutable' {
  declare module.exports: any;
}

declare module 'seamless-immutable/test/ImmutableArray/test-asObject' {
  declare module.exports: any;
}

declare module 'seamless-immutable/test/ImmutableArray/test-compat' {
  declare module.exports: any;
}

declare module 'seamless-immutable/test/ImmutableArray/test-flatMap' {
  declare module.exports: any;
}

declare module 'seamless-immutable/test/ImmutableArray/test-set' {
  declare module.exports: any;
}

declare module 'seamless-immutable/test/ImmutableArray/test-update' {
  declare module.exports: any;
}

declare module 'seamless-immutable/test/ImmutableDate.spec' {
  declare module.exports: any;
}

declare module 'seamless-immutable/test/ImmutableDate/test-asMutable' {
  declare module.exports: any;
}

declare module 'seamless-immutable/test/ImmutableDate/test-compat' {
  declare module.exports: any;
}

declare module 'seamless-immutable/test/ImmutableObject.spec' {
  declare module.exports: any;
}

declare module 'seamless-immutable/test/ImmutableObject/test-asMutable' {
  declare module.exports: any;
}

declare module 'seamless-immutable/test/ImmutableObject/test-compat' {
  declare module.exports: any;
}

declare module 'seamless-immutable/test/ImmutableObject/test-instantiateEmptyObject' {
  declare module.exports: any;
}

declare module 'seamless-immutable/test/ImmutableObject/test-merge' {
  declare module.exports: any;
}

declare module 'seamless-immutable/test/ImmutableObject/test-replace' {
  declare module.exports: any;
}

declare module 'seamless-immutable/test/ImmutableObject/test-set' {
  declare module.exports: any;
}

declare module 'seamless-immutable/test/ImmutableObject/test-update' {
  declare module.exports: any;
}

declare module 'seamless-immutable/test/ImmutableObject/test-without' {
  declare module.exports: any;
}

declare module 'seamless-immutable/test/TestUtils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'seamless-immutable/benchmark.js' {
  declare module.exports: $Exports<'seamless-immutable/benchmark'>;
}
declare module 'seamless-immutable/Gruntfile.js' {
  declare module.exports: $Exports<'seamless-immutable/Gruntfile'>;
}
declare module 'seamless-immutable/seamless-immutable.development.js' {
  declare module.exports: $Exports<'seamless-immutable/seamless-immutable.development'>;
}
declare module 'seamless-immutable/seamless-immutable.development.min.js' {
  declare module.exports: $Exports<'seamless-immutable/seamless-immutable.development.min'>;
}
declare module 'seamless-immutable/seamless-immutable.production.min.js' {
  declare module.exports: $Exports<'seamless-immutable/seamless-immutable.production.min'>;
}
declare module 'seamless-immutable/src/seamless-immutable.js' {
  declare module.exports: $Exports<'seamless-immutable/src/seamless-immutable'>;
}
declare module 'seamless-immutable/test/Immutable.isImmutable.spec.js' {
  declare module.exports: $Exports<'seamless-immutable/test/Immutable.isImmutable.spec'>;
}
declare module 'seamless-immutable/test/Immutable.spec.js' {
  declare module.exports: $Exports<'seamless-immutable/test/Immutable.spec'>;
}
declare module 'seamless-immutable/test/ImmutableArray.spec.js' {
  declare module.exports: $Exports<'seamless-immutable/test/ImmutableArray.spec'>;
}
declare module 'seamless-immutable/test/ImmutableArray/test-asMutable.js' {
  declare module.exports: $Exports<'seamless-immutable/test/ImmutableArray/test-asMutable'>;
}
declare module 'seamless-immutable/test/ImmutableArray/test-asObject.js' {
  declare module.exports: $Exports<'seamless-immutable/test/ImmutableArray/test-asObject'>;
}
declare module 'seamless-immutable/test/ImmutableArray/test-compat.js' {
  declare module.exports: $Exports<'seamless-immutable/test/ImmutableArray/test-compat'>;
}
declare module 'seamless-immutable/test/ImmutableArray/test-flatMap.js' {
  declare module.exports: $Exports<'seamless-immutable/test/ImmutableArray/test-flatMap'>;
}
declare module 'seamless-immutable/test/ImmutableArray/test-set.js' {
  declare module.exports: $Exports<'seamless-immutable/test/ImmutableArray/test-set'>;
}
declare module 'seamless-immutable/test/ImmutableArray/test-update.js' {
  declare module.exports: $Exports<'seamless-immutable/test/ImmutableArray/test-update'>;
}
declare module 'seamless-immutable/test/ImmutableDate.spec.js' {
  declare module.exports: $Exports<'seamless-immutable/test/ImmutableDate.spec'>;
}
declare module 'seamless-immutable/test/ImmutableDate/test-asMutable.js' {
  declare module.exports: $Exports<'seamless-immutable/test/ImmutableDate/test-asMutable'>;
}
declare module 'seamless-immutable/test/ImmutableDate/test-compat.js' {
  declare module.exports: $Exports<'seamless-immutable/test/ImmutableDate/test-compat'>;
}
declare module 'seamless-immutable/test/ImmutableObject.spec.js' {
  declare module.exports: $Exports<'seamless-immutable/test/ImmutableObject.spec'>;
}
declare module 'seamless-immutable/test/ImmutableObject/test-asMutable.js' {
  declare module.exports: $Exports<'seamless-immutable/test/ImmutableObject/test-asMutable'>;
}
declare module 'seamless-immutable/test/ImmutableObject/test-compat.js' {
  declare module.exports: $Exports<'seamless-immutable/test/ImmutableObject/test-compat'>;
}
declare module 'seamless-immutable/test/ImmutableObject/test-instantiateEmptyObject.js' {
  declare module.exports: $Exports<'seamless-immutable/test/ImmutableObject/test-instantiateEmptyObject'>;
}
declare module 'seamless-immutable/test/ImmutableObject/test-merge.js' {
  declare module.exports: $Exports<'seamless-immutable/test/ImmutableObject/test-merge'>;
}
declare module 'seamless-immutable/test/ImmutableObject/test-replace.js' {
  declare module.exports: $Exports<'seamless-immutable/test/ImmutableObject/test-replace'>;
}
declare module 'seamless-immutable/test/ImmutableObject/test-set.js' {
  declare module.exports: $Exports<'seamless-immutable/test/ImmutableObject/test-set'>;
}
declare module 'seamless-immutable/test/ImmutableObject/test-update.js' {
  declare module.exports: $Exports<'seamless-immutable/test/ImmutableObject/test-update'>;
}
declare module 'seamless-immutable/test/ImmutableObject/test-without.js' {
  declare module.exports: $Exports<'seamless-immutable/test/ImmutableObject/test-without'>;
}
declare module 'seamless-immutable/test/TestUtils.js' {
  declare module.exports: $Exports<'seamless-immutable/test/TestUtils'>;
}
