// flow-typed signature: 6be1cedcbf534322452373aeeb53e71e
// flow-typed version: <<STUB>>/testem_v^1.10.2/flow_v0.30.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'testem'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'testem' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'testem/assets/phantom' {
  declare module.exports: any;
}

declare module 'testem/lib/add-to-PATH' {
  declare module.exports: any;
}

declare module 'testem/lib/api' {
  declare module.exports: any;
}

declare module 'testem/lib/app' {
  declare module.exports: any;
}

declare module 'testem/lib/browser_launcher' {
  declare module.exports: any;
}

declare module 'testem/lib/browser_tap_consumer' {
  declare module.exports: any;
}

declare module 'testem/lib/chars' {
  declare module.exports: any;
}

declare module 'testem/lib/clean_exit' {
  declare module.exports: any;
}

declare module 'testem/lib/config' {
  declare module.exports: any;
}

declare module 'testem/lib/displayutils' {
  declare module.exports: any;
}

declare module 'testem/lib/env-with-local-path' {
  declare module.exports: any;
}

declare module 'testem/lib/file_watcher' {
  declare module.exports: any;
}

declare module 'testem/lib/fileutils' {
  declare module.exports: any;
}

declare module 'testem/lib/hook_runner' {
  declare module.exports: any;
}

declare module 'testem/lib/isa' {
  declare module.exports: any;
}

declare module 'testem/lib/launcher-factory' {
  declare module.exports: any;
}

declare module 'testem/lib/launcher' {
  declare module.exports: any;
}

declare module 'testem/lib/process-ctl' {
  declare module.exports: any;
}

declare module 'testem/lib/reporters/dev/constants' {
  declare module.exports: any;
}

declare module 'testem/lib/reporters/dev/error_messages_panel' {
  declare module.exports: any;
}

declare module 'testem/lib/reporters/dev/index' {
  declare module.exports: any;
}

declare module 'testem/lib/reporters/dev/patchcharm' {
  declare module.exports: any;
}

declare module 'testem/lib/reporters/dev/runner_tabs' {
  declare module.exports: any;
}

declare module 'testem/lib/reporters/dev/runner' {
  declare module.exports: any;
}

declare module 'testem/lib/reporters/dev/screen' {
  declare module.exports: any;
}

declare module 'testem/lib/reporters/dev/scrollable_text_panel' {
  declare module.exports: any;
}

declare module 'testem/lib/reporters/dev/split_log_panel' {
  declare module.exports: any;
}

declare module 'testem/lib/reporters/dev/test_results' {
  declare module.exports: any;
}

declare module 'testem/lib/reporters/dev/view' {
  declare module.exports: any;
}

declare module 'testem/lib/reporters/dot_reporter' {
  declare module.exports: any;
}

declare module 'testem/lib/reporters/index' {
  declare module.exports: any;
}

declare module 'testem/lib/reporters/tap_reporter' {
  declare module.exports: any;
}

declare module 'testem/lib/reporters/teamcity_reporter' {
  declare module.exports: any;
}

declare module 'testem/lib/reporters/xunit_reporter' {
  declare module.exports: any;
}

declare module 'testem/lib/runners/browser_test_runner' {
  declare module.exports: any;
}

declare module 'testem/lib/runners/process_test_runner' {
  declare module.exports: any;
}

declare module 'testem/lib/runners/tap_process_test_runner' {
  declare module.exports: any;
}

declare module 'testem/lib/server/index' {
  declare module.exports: any;
}

declare module 'testem/lib/strutils' {
  declare module.exports: any;
}

declare module 'testem/lib/tap_consumer' {
  declare module.exports: any;
}

declare module 'testem/lib/utils/browser-args' {
  declare module.exports: any;
}

declare module 'testem/lib/utils/capitalize' {
  declare module.exports: any;
}

declare module 'testem/lib/utils/known-browsers' {
  declare module.exports: any;
}

declare module 'testem/lib/utils/report-file' {
  declare module.exports: any;
}

declare module 'testem/lib/utils/reporter' {
  declare module.exports: any;
}

declare module 'testem/lib/utils/run-timeout' {
  declare module.exports: any;
}

declare module 'testem/lib/utils/signal-listeners' {
  declare module.exports: any;
}

declare module 'testem/public/testem/buster_adapter' {
  declare module.exports: any;
}

declare module 'testem/public/testem/decycle' {
  declare module.exports: any;
}

declare module 'testem/public/testem/jasmine_adapter' {
  declare module.exports: any;
}

declare module 'testem/public/testem/jasmine2_adapter' {
  declare module.exports: any;
}

declare module 'testem/public/testem/mocha_adapter' {
  declare module.exports: any;
}

declare module 'testem/public/testem/qunit_adapter' {
  declare module.exports: any;
}

declare module 'testem/public/testem/testem_client' {
  declare module.exports: any;
}

declare module 'testem/public/testem/testem_connection' {
  declare module.exports: any;
}

declare module 'testem/testem' {
  declare module.exports: any;
}

// Filename aliases
declare module 'testem/assets/phantom.js' {
  declare module.exports: $Exports<'testem/assets/phantom'>;
}
declare module 'testem/lib/add-to-PATH.js' {
  declare module.exports: $Exports<'testem/lib/add-to-PATH'>;
}
declare module 'testem/lib/api.js' {
  declare module.exports: $Exports<'testem/lib/api'>;
}
declare module 'testem/lib/app.js' {
  declare module.exports: $Exports<'testem/lib/app'>;
}
declare module 'testem/lib/browser_launcher.js' {
  declare module.exports: $Exports<'testem/lib/browser_launcher'>;
}
declare module 'testem/lib/browser_tap_consumer.js' {
  declare module.exports: $Exports<'testem/lib/browser_tap_consumer'>;
}
declare module 'testem/lib/chars.js' {
  declare module.exports: $Exports<'testem/lib/chars'>;
}
declare module 'testem/lib/clean_exit.js' {
  declare module.exports: $Exports<'testem/lib/clean_exit'>;
}
declare module 'testem/lib/config.js' {
  declare module.exports: $Exports<'testem/lib/config'>;
}
declare module 'testem/lib/displayutils.js' {
  declare module.exports: $Exports<'testem/lib/displayutils'>;
}
declare module 'testem/lib/env-with-local-path.js' {
  declare module.exports: $Exports<'testem/lib/env-with-local-path'>;
}
declare module 'testem/lib/file_watcher.js' {
  declare module.exports: $Exports<'testem/lib/file_watcher'>;
}
declare module 'testem/lib/fileutils.js' {
  declare module.exports: $Exports<'testem/lib/fileutils'>;
}
declare module 'testem/lib/hook_runner.js' {
  declare module.exports: $Exports<'testem/lib/hook_runner'>;
}
declare module 'testem/lib/isa.js' {
  declare module.exports: $Exports<'testem/lib/isa'>;
}
declare module 'testem/lib/launcher-factory.js' {
  declare module.exports: $Exports<'testem/lib/launcher-factory'>;
}
declare module 'testem/lib/launcher.js' {
  declare module.exports: $Exports<'testem/lib/launcher'>;
}
declare module 'testem/lib/process-ctl.js' {
  declare module.exports: $Exports<'testem/lib/process-ctl'>;
}
declare module 'testem/lib/reporters/dev/constants.js' {
  declare module.exports: $Exports<'testem/lib/reporters/dev/constants'>;
}
declare module 'testem/lib/reporters/dev/error_messages_panel.js' {
  declare module.exports: $Exports<'testem/lib/reporters/dev/error_messages_panel'>;
}
declare module 'testem/lib/reporters/dev/index.js' {
  declare module.exports: $Exports<'testem/lib/reporters/dev/index'>;
}
declare module 'testem/lib/reporters/dev/patchcharm.js' {
  declare module.exports: $Exports<'testem/lib/reporters/dev/patchcharm'>;
}
declare module 'testem/lib/reporters/dev/runner_tabs.js' {
  declare module.exports: $Exports<'testem/lib/reporters/dev/runner_tabs'>;
}
declare module 'testem/lib/reporters/dev/runner.js' {
  declare module.exports: $Exports<'testem/lib/reporters/dev/runner'>;
}
declare module 'testem/lib/reporters/dev/screen.js' {
  declare module.exports: $Exports<'testem/lib/reporters/dev/screen'>;
}
declare module 'testem/lib/reporters/dev/scrollable_text_panel.js' {
  declare module.exports: $Exports<'testem/lib/reporters/dev/scrollable_text_panel'>;
}
declare module 'testem/lib/reporters/dev/split_log_panel.js' {
  declare module.exports: $Exports<'testem/lib/reporters/dev/split_log_panel'>;
}
declare module 'testem/lib/reporters/dev/test_results.js' {
  declare module.exports: $Exports<'testem/lib/reporters/dev/test_results'>;
}
declare module 'testem/lib/reporters/dev/view.js' {
  declare module.exports: $Exports<'testem/lib/reporters/dev/view'>;
}
declare module 'testem/lib/reporters/dot_reporter.js' {
  declare module.exports: $Exports<'testem/lib/reporters/dot_reporter'>;
}
declare module 'testem/lib/reporters/index.js' {
  declare module.exports: $Exports<'testem/lib/reporters/index'>;
}
declare module 'testem/lib/reporters/tap_reporter.js' {
  declare module.exports: $Exports<'testem/lib/reporters/tap_reporter'>;
}
declare module 'testem/lib/reporters/teamcity_reporter.js' {
  declare module.exports: $Exports<'testem/lib/reporters/teamcity_reporter'>;
}
declare module 'testem/lib/reporters/xunit_reporter.js' {
  declare module.exports: $Exports<'testem/lib/reporters/xunit_reporter'>;
}
declare module 'testem/lib/runners/browser_test_runner.js' {
  declare module.exports: $Exports<'testem/lib/runners/browser_test_runner'>;
}
declare module 'testem/lib/runners/process_test_runner.js' {
  declare module.exports: $Exports<'testem/lib/runners/process_test_runner'>;
}
declare module 'testem/lib/runners/tap_process_test_runner.js' {
  declare module.exports: $Exports<'testem/lib/runners/tap_process_test_runner'>;
}
declare module 'testem/lib/server/index.js' {
  declare module.exports: $Exports<'testem/lib/server/index'>;
}
declare module 'testem/lib/strutils.js' {
  declare module.exports: $Exports<'testem/lib/strutils'>;
}
declare module 'testem/lib/tap_consumer.js' {
  declare module.exports: $Exports<'testem/lib/tap_consumer'>;
}
declare module 'testem/lib/utils/browser-args.js' {
  declare module.exports: $Exports<'testem/lib/utils/browser-args'>;
}
declare module 'testem/lib/utils/capitalize.js' {
  declare module.exports: $Exports<'testem/lib/utils/capitalize'>;
}
declare module 'testem/lib/utils/known-browsers.js' {
  declare module.exports: $Exports<'testem/lib/utils/known-browsers'>;
}
declare module 'testem/lib/utils/report-file.js' {
  declare module.exports: $Exports<'testem/lib/utils/report-file'>;
}
declare module 'testem/lib/utils/reporter.js' {
  declare module.exports: $Exports<'testem/lib/utils/reporter'>;
}
declare module 'testem/lib/utils/run-timeout.js' {
  declare module.exports: $Exports<'testem/lib/utils/run-timeout'>;
}
declare module 'testem/lib/utils/signal-listeners.js' {
  declare module.exports: $Exports<'testem/lib/utils/signal-listeners'>;
}
declare module 'testem/public/testem/buster_adapter.js' {
  declare module.exports: $Exports<'testem/public/testem/buster_adapter'>;
}
declare module 'testem/public/testem/decycle.js' {
  declare module.exports: $Exports<'testem/public/testem/decycle'>;
}
declare module 'testem/public/testem/jasmine_adapter.js' {
  declare module.exports: $Exports<'testem/public/testem/jasmine_adapter'>;
}
declare module 'testem/public/testem/jasmine2_adapter.js' {
  declare module.exports: $Exports<'testem/public/testem/jasmine2_adapter'>;
}
declare module 'testem/public/testem/mocha_adapter.js' {
  declare module.exports: $Exports<'testem/public/testem/mocha_adapter'>;
}
declare module 'testem/public/testem/qunit_adapter.js' {
  declare module.exports: $Exports<'testem/public/testem/qunit_adapter'>;
}
declare module 'testem/public/testem/testem_client.js' {
  declare module.exports: $Exports<'testem/public/testem/testem_client'>;
}
declare module 'testem/public/testem/testem_connection.js' {
  declare module.exports: $Exports<'testem/public/testem/testem_connection'>;
}
declare module 'testem/testem.js' {
  declare module.exports: $Exports<'testem/testem'>;
}
